---
title: "Reproducible Research: Peer Assessment 1"
output: html_document 
---


## Loading and preprocessing the data
#### Download and unzip file, then upload the file into R 
```
library(readr)
activity <- read_csv("~/DataScience/Rep Research/activity.csv")
View(activity)
```
#### Preprocessing data
```
activity$day <- weekdays(as.Date(activity$date))
activity$DateTime<- as.POSIXct(activity$date, format="%Y-%m-%d")
```
####Pulling data without nas
```
clean <- activity[!is.na(activity$steps),]
```

## What is mean total number of steps taken per day?

#### Sum Steps by day and makes and histogram
```
stepsbyday <- aggregate(steps ~ date, activity, sum)
hist(stepsbyday$steps, main = paste("Total Steps Per Day"), col="red", xlab="Count of Steps")
```
![] (https://github.com/Scotturbina/RepData_PeerAssessment1/blob/master/instructions_fig/total%20steps%20each%20day.png)

#### Calculating mean and median of steps per day
```
rmean <- mean(stepsbyday$steps)
rmedian <- median(stepsbyday$steps)
```

## What is the average daily activity pattern?
#### Take the invertal mean steps
```
stepsinterval <- aggregate(steps ~ interval, activity, mean)
```
#### Plot the mean interval
```
plot(stepsinterval$interval,stepsinterval$steps, type="l", xlab="Interval", ylab="Number of Steps",main="Average Number of Steps per Day Interval", col="blue")
```
![] (https://github.com/Scotturbina/RepData_PeerAssessment1/blob/master/instructions_fig/Average%20steps%20per%20interval.png)
#### Take the maximun interval
```
max_interval <- stepsinterval[which.max(stepsinterval$steps),1]
max_interval
```


## Imputing missing values

####Find incomplete cases and sum
```
incomp <- sum(!complete.cases(activity))
imputeddat <- transform(activity, steps = ifelse(is.na(activity$steps), stepsinterval$steps[match(activity$interval, stepsinterval$interval)], activity$steps))
imputeddat[as.character(imputeddat$date) == "2012-10-01", 1] <- 0
```
#### Re count steps and creates an histogram
```
stepsbydayi <- aggregate(steps ~ date, imputeddat, sum)
hist(stepsbydayi$steps, main = paste("Total Steps Each Day"), col="blue", xlab="Number of Steps")
```
####Create Histogram to show difference.
```
hist(stepsbyday_i$steps, main = paste("Total Steps of Each Day"), col="blue", xlab="count of Steps", add=T)
legend("topright", c("Imputed", "Non-imputed"), col=c("blue", "red"), lwd=10)
```

####Calcute media and mean for imputed data
```
rmean.i <- mean(stepsbydayi$steps)
rmedian.i <- median(stepsbydayi$steps)
```

####calculate diffence between inputed and non imputed data
```
mean_diff <- rmean.i - rmean
med_diff <- rmedian.i - rmedian
```
## Are there differences in activity patterns between weekdays and weekends?

####compare average steps by interval by weekend and weekday
```
weekdays <- c("Monday", "Tuesday", "Wednesday", "Thursday", 
              "Friday")
imputeddat$dow = as.factor(ifelse(is.element(weekdays(as.Date(imputeddat$date)),weekdays), "Weekday", "Weekend"))

stepsbyintervali <- aggregate(steps ~ interval + dow, imputeddat, mean)
```
####Plot the comparison
```
require(lattice)

xyplot(stepsbyintervali$steps ~ stepsbyintervali$interval|stepsbyintervali$dow, main="Average Steps per Day by Interval",xlab="Interval", ylab="Number Steps",layout=c(1,2), type="l")
```



